export const AGREGAR_USUARIO = 'agregar_usuario'
export const FACEBOOK_LOGIN_FAIL = 'facebook_login_fail'
export const FETCH_JOBS = 'fetch_jobs'
export const LIKE_JOB = 'like_job'
export const FETCH_CATEGORIAS = 'fetch_categorias'
